#!/usr/bin/env bash
#.h
while IFS=':' read -r username password userid groupid userdesc homedir shell || [[ -n "$username" ]]
do
    echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $userdesc"
    echo
done < /etc/passwd

