#!/usr/bin/env bash
#..
hour=0
while [ $hour -lt 13 ]; do
    minute=1
    while [ $minute -lt 60 ]; do
        echo "Hour: $hour"
        echo "$minute"
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
done | head -n 70

