#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
hour=0
HOUR=12
min=1
MIN=59
while [ $hour -le $HOUR ];
do
	echo "Hour: $hour"
	((min = 1))
	while [ $min -le $MIN ];
	do
		echo "$min"
		((min++))
	done
	((hour++))
done
