#!/usr/bin/env bash
#..
hour=0
minute=1

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    while [ $minute -le 59 ]
    do
        echo "$minute"
        minute=$((minute + 1))
        if [ $minute -eq 60 ]
        then
            minute=0
            break
        fi
    done

    hour=$((hour + 1))
done | head -n 70

