#!/usr/bin/env bash
#..
start() {
	if [ -f "/var/run/my_proces.pid" ]; then
		echo "manage_my_process is already running with PID $(cat /var/run/my_process.pid)"
	else
      	./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop() {
    if [ -f "/var/run/my_process.pid" ]; then
        pid=$(cat /var/run/my_process.pid)
        kill "$pid"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

if [ $# -ne 1 ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
else
    case $1 in
        "start")
            start
            ;;
        "stop")
            stop
            ;;
        "restart")
            restart
            ;;
        *)
            echo "Usage: manage_my_process {start|stop|restart}"
            ;;
    esac
fi

