#!/usr/bin/env bash
# Search for processes containing the word "bash"
for pid in /proc/*/status; do
    if grep -q "Name:\s*bash" "$pid"; then
       pid=$(basename "$(dirname "$pid")")
        name=$(tr -d '\0' < "/proc/$pid/cmdline")
        echo "$pid $name"
    fi
done

